uktrade/ci-image-builder

- build.sh
- Update script to explicitly use `buildpacks` key for buildpack images.
- This makes sure the `buildpack.json` file contains the `buildpacks` key and is consistent.
> Update build script to use `buildpacks` key

- build.sh
Provide option to pass in BUILDER_VERSION as env variable, rather than hardcoding it.
> DBTP-137 Support different tagged versions in `ci-image-builder` repo

- build.sh
Trusted advisor complains that we have ecr repos not using image scanning:
Separate task to switch it on for existing repos
> pass image-scanning-configuration flag

- Dockerfile
- README.md
- build.sh
- buildspec.yml
- Make `BUILDER_VERSION` more apparent, so we know it is the Paketo builder version.
- There was confusion around whether it was the `ci-image-builder` version or the Paketo builder version.
> Refactor: Rename `BUILDER_VERSION` -> `PAKETO_BUILDER_VERSION`

- build.sh
If the buildpack JSON file is missing or does not contain any buildpacks, fail the build.
Currently a build with no buildpacks will produce a useless image without buildpacks.
Add `exit 1` to each failure condition.
> fix: fail a build with no buildpacks

- README.md
- buildspec.yml
- Add `PACK_VERSION` to buildspec configuration
- Terraform manages the CodeBuild project, so manually adding the env var in the CodeBuild console will mean it gets removed upon every `terraform apply` as it is not set there.
- Update documentation
> Add `PACK_VERSION` to buildspec configuration

- build.sh
So that we can reliably select the tag that matches `latest` from a  Python List of ECR tags like `['6a1e3d2', 'latest', 'main']`.
> DBTP-459 Prefix commit/branch tags & get more robust commit SHA

- README.md
- Remove `buildspec` reference in README.md
- This is no longer required as this is taken care of elsewhere.
- Update README.md with `copilot-helper codebase prepare` command
- This will automatically generate the required files/folder structure.
> Remove reference to `buildspec` from README.md

- image_builder/commands.py
- image_builder/notify.py
- image_builder/pack.py
- test/image_builder/test_commands.py
- test/image_builder/test_notify.py
- test/image_builder/test_pack.py
- Add a command argument to allow users to build locally without sending notifications.
- Override OCI labels from paketo
- `org.opencontainers.image.revision` - commit sha
- `org.opencontainers.image.version` - commit sha
- `org.opencontainers.image.ref.name` - ecr repo name
- `org.opencontainers.image.source` - add url to git repository
- `uk.gov.trade.digital.build.timestamp` - only used when building remotely
> DBTP-386 - Add OCI labels to built images for fun and other reasons

- Dockerfile
Adding some tools so we can use the ci-image-builder image in our deploy jobs, saving install time.
Adds copilot cli so we don't have to install it as part of the deploy scripts.
Adds regctl as this allows us to show information about the built image without issuing a `docker pull`.
> DBTP-464 Install copilot and regctl

- image_builder/configuration/codebase.py
- image_builder/pack.py
- test/fixtures/codebase/missing-repository/.copilot/config.yml
- test/image_builder/configuration/test_codebase_configuration.py
- test/image_builder/test_pack.py
- Allow overriding the `Pack().get_repository_url()` return value with an environment variable `ECR_REPOSITORY`
- Allow build configurations without `repository` property
> DBTP-586 allow setting ecr repo from environment

- .gitignore
- image_builder/commands/build.py
- image_builder/commands/deploy.py
- image_builder/notify.py
- image_builder/progress.py
- test/image_builder/commands/test_build.py
- test/image_builder/commands/test_deploy.py
- test/image_builder/test_notify.py
- Update build and deploy notifications to be compact
- This removes the ECR image from the deployment notifications, but this has now moved to the build notification which contains all the details.
> DBTP-609 - Compact build and deploy notifications

- image_builder/codebase/revision.py
- test/image_builder/codebase/test_revision.py
Currently, if the commit we are building is not the head commit for a branch but is part of a branch, the image will be tagged with the branch name. This approach uses `git show-ref --heads` to get the head commit of each branch to match on.
> DBTP-618 only tag with branch if head commit

- Dockerfile
- image_builder/commands/deploy.py
- test/image_builder/commands/test_deploy.py
[DBTP-763](https://uktrade.atlassian.net/browse/DBTP-763) & [DBTP-783](https://uktrade.atlassian.net/browse/DBTP-783)
- Remove pre-installed copilot version from image
- Pre-download recent copilot versions to speed up deployments
- Use correct pre-installed version or install the correct version of copilot when deploying services
[DBTP-763]: https://uktrade.atlassian.net/browse/DBTP-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DBTP-783]: https://uktrade.atlassian.net/browse/DBTP-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: DBTP-763 - Install correct version of copilot

- .github/workflows/on_push.yml
- image_builder/codebase/codebase.py
- image_builder/configuration/builder_configuration.yml
- image_builder/pack.py
- test/image_builder/test_pack.py
The apt buildpack is only compatible with buildpack API version `0.4` whereas the buildpack for python `3.12` depends on a builder version that only supports buildpack API version `0.7` and above. To work around this for the moment, we only add the apt buildpack if explicitly configuring a list of packages to install.
> fix: only add apt buildpack if packages in config

- image_builder/commands/deploy.py
- test/image_builder/commands/test_deploy.py
- Send slack notification if copilot version specified in deploy repository
- Is not cached in the `ci-image-builder`
- Is not the latest copilot version
> feat: DBTP-765 - copilot version notifications

- image_builder/codebase/codebase.py
- image_builder/codebase/load_run_environment.sh
- image_builder/configuration/builder_configuration.yml
- test/image_builder/codebase/test_codebase.py
- moves the build run script to it's own bash file
- supports the latest builder versions
> feat: support non pip installations

- image_builder/pack.py
- test/image_builder/test_pack.py
When we raise a `PackCommandFailedError` include the contents of `stderr` in the output and notification.
> Output stderr from pack command in exception

- image_builder/pack.py
- test/doubles/fake_pack_fail.sh
- test/image_builder/test_pack.py
this is due to a maximum of 3000 chars in a slack notification additional prefixing of the error message means 2500 characters is a safe option to use
> fix: truncate to only show last 2500 characters of error

- image_builder/pack.py
- check if output has a decode function on it (is a byte array)
- remove erroneous print statement
> check if output is a byte array before trying to decode

- Dockerfile
So it's preinstalled to speed up builds.
> Add AWS Copilot 1.33.4

- Dockerfile
- image_builder/configuration/builder_configuration.yml
- install-dependencies-for-all-pythons.sh
Motivated by a desire to support the latest Python release, 3.12.5 I added the latest builder-jammy-full.
Then @james-francis-MT and I discovered that the versions of Python we were trying to use in our respective codebases where not installed on this image. Workaround for that was for me to go down one patch number and @james-francis-MT to go up one.
Next problem was when it tried to send the Slack notification using Python 3.12. Turn out the Slack SDK was installed under Python 3.11 and not available when the command was called using Python 3.12.
I've added a script to install the dependencies for all installed Python versions when the image is built, so that they are available to be used as required at runtime. This adds about 15MB, but to a 4GB image, so insignificant.
> DBTP-1327 Add builder-jammy-full 0.3.397 & install dependencies for all Pythons

- README.md
- buildspec.yml
To reduce risk of ruining loads of people's day by allowing them and us to use `tag-latest` to reference the latest stable release in our pipelines.
Example tagged images:
Untagged commit
Tagged commit
> Make tagging conform to our standard approach more closely

- buildspec.yml
- image_builder/codebase/revision.py
- image_builder/pack.py
- test/doubles/codebase.py
- test/image_builder/codebase/test_revision.py
- test/image_builder/test_pack.py
Add environment variables required during run time for DataDog codebase tracking.
DD_VERSION: <short-git-commit/git-tag>
DD_GIT_COMMIT_SHA: <long-git-commit>
DD_GIT_REPOSITORY_URL: <git-repository-url>
> feat: dbtp 1659 datadog

- image_builder/pack.py
- test/image_builder/test_pack.py
Addresses errors seen in build jobs:
```shell
Error: ERROR: failed to build: downloading buildpack: extracting from registry 'gcr.io/paketo-buildpacks/image-labels': fetching image: connect to repo store "gcr.io/paketo-buildpacks/image-labels"
```
---
~~- [ ] Link to ticket included (unless it's a quick out of ticket thing)~~
~~- [ ] Includes any applicable changes to the documentation in this code base~~
~~- [ ] Includes link(s) to any applicable changes to the documentation in the [DBT Platform Documentation](https://platform.readme.trade.gov.uk/) (can be to a pull request)~~
> fix: Buildpack images not found (off-ticket)
